### ISSUE TITLE
Wrong word "БезопасТность" in node-hero/README.md

### ISSUE THREAD

**Issue by geek10010** [devSchacht/translations#157]
to @amel-true 
Андрей, в "Содержании" книги https://github.com/devSchacht/translations/blob/master/node-hero/README.md исправьте, пожалуйста, "Безопастность" на "Безопасность" (без "т"). 
Аналогично в https://github.com/devSchacht/translations/blob/master/node-hero/full_book.md

**Comment by amel-true** [comment]
Спасибо, поправил
