### ISSUE TITLE
"Форте Пеано": cломана ссылка на статью на medium

### ISSUE THREAD

**Issue by archangel-irk** [devSchacht/translations#50]
В конце статьи https://github.com/devSchacht/translations/tree/master/tom-harding-peanos-forte есть ссылка "Статья на Medium", которая сейчас не работает.

P.S. Большое спасибо за проделанный вами труд.

Могу сделать PR, если это уместно.

**Comment by yalovek** [comment]
Спасибо, поправил! И если будет желание, то конечно же делай PR'ы. Мы к этому открыты)

**Comment by archangel-irk** [comment]
Спасибо.
Желание есть, времени не всегда находится. Но я постараюсь. Считаю очень важным наличие качественного материала и его распространение.
