### ISSUE TITLE
README.md: Не хватает нескольких ссылок на статьи

### ISSUE THREAD

**Issue by archangel-irk** [devSchacht/translations#51]
Кажется, есть ещё две статьи, которые не упомянуты в readme.

1. Спецификация Fantasy Land
2. Спецификация Static Land

Могу сделать PR, если это уместно.

**Comment by yalovek** [comment]
Привет, а они у нас в отдельных репах)

https://github.com/devSchacht/fantasy-land
https://github.com/devSchacht/static-land

**Comment by archangel-irk** [comment]
Упс, не заметил, спасибо. Я понял что это сделано из-за преимуществ форка. А может быть ссылку в readme стоит добавить? Чтобы консистентность была.

Мой путь был такой. Я открыл список всех переводов https://github.com/devSchacht/translations/blob/master/README.md, но обнаружил что пары переводов не хватает, и оказался в недоумении, так как я точно видел их на сайте.

**Comment by archangel-irk** [comment]
Привет, здорово. :) Спасибо.
